import type { GetServerSideProps, GetStaticProps, GetStaticPropsContext, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Search from "../components/Search";
import SelectRg from "../components/SelectRg";
import Cards from "../components/Cards";
import { useEffect, useState } from "react";

const Home: NextPage = (props) => {
  console.log(props.data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>
        <div className="container mx-auto mt-10 max-w-sm md:max-w-screen-md lg:max-w-screen-lg flex flex-col items-center justify-between md:flex-row space-y-5 md:space-y-0 md:justify-between">
          <Search />
          <SelectRg />
        </div>
        <Cards />
      </main>
    </div>
  );
};

export const getStaticProps = async () => {
  const res = await fetch("https://restcountries.com/v3.1/all");
  const countries: any = await res.json()
  return {
    props: { countries },
  };
}

export default Home;
