import Head from "next/head";
import Navbar from "../components/Navbar";
import Search from "../components/Search";
import SelectRg from "../components/SelectRg";
import Cards from "../components/Cards";
import { NextPage } from "next";
import axios from "axios";
import { useState } from "react";

const Home: NextPage = ({ countries }: any) => {
  const [countryName, setCountryName] = useState();
  const callback = (name:any) => {
    setCountryName(name)
  };

  console.log(countryName);
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto mt-10 max-w-sm md:max-w-screen-md lg:max-w-screen-lg flex flex-col items-center justify-between md:flex-row space-y-5 md:space-y-0 md:justify-between xl:max-w-screen-xl">
        <Search onSubmit={callback} />
        <SelectRg />
      </div>
      <Cards countries={countries} countryName={countryName} />
    </div>
  );
};
export const getServerSideProps = async () => {
  const countries = await axios.get("https://restcountries.com/v3.1/all");
  return {
    props: { countries: countries.data },
  };
};

export default Home;
